[app]
debug=false
dbname="idfp"
dbhost="localhost"
dbport=5432
dbuser="idfp"
dbpassword="dbpassword"
dbreaderuser="idfp"
dbreaderpassword="dbpassword"
web_bind=['localhost:6969']
web_preload=true
web_reuse_port=true
web_workers=4

[logging]
[logging.loggers.idfp]
level="INFO"
handlers=["hand01"]
propagate=1

[logging.loggers."gunicorn.access"]
level="INFO"
handlers=["hand01"]
propagate=1
qualname="gunicorn.access"

[logging.loggers."gunicorn.error"]
level="INFO"
handlers=["hand02"]
propagate=1
qualname="gunicorn.error"

[logging.handlers.hand01]
class="logging.StreamHandler"
level="NOTSET"
formatter="form01"
stream="ext://sys.stdout"

[logging.handlers.hand02]
class="logging.StreamHandler"
level="NOTSET"
formatter="form01"
stream="ext://sys.stderr"

[logging.formatters.form01]
format="%(asctime)s [%(process)d] [%(name)s] [%(levelname)s] %(message)s"
datefmt="[%Y-%m-%d %H:%M:%S %z]"
class="logging.Formatter"
